"""empty message

Revision ID: 503f53cdf5ea
Revises: b14b3f326b82
Create Date: 2021-05-01 00:36:17.868408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503f53cdf5ea'
down_revision = 'b14b3f326b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_symbol', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    # ### end Alembic commands ###
