"""empty message

Revision ID: b14b3f326b82
Revises: eebab543830c
Create Date: 2021-04-30 23:30:48.872270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14b3f326b82'
down_revision = 'eebab543830c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('ticker_symbol', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('ticker_symbol'),
    sa.UniqueConstraint('ticker_symbol')
    )
    op.create_unique_constraint(None, 'portfolio', ['ticker_symbol'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='unique')
    op.drop_table('trades')
    # ### end Alembic commands ###
