"""empty message

Revision ID: eebab543830c
Revises: 
Create Date: 2021-04-30 23:23:06.363517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebab543830c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('ticker_symbol', sa.String(length=255), nullable=False),
    sa.Column('avg_buy_price', sa.Float(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ticker_symbol'),
    sa.UniqueConstraint('ticker_symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    # ### end Alembic commands ###
